//! Autogenerated OpenAPI 3.1 document from the live function route table.
//!
//! The same walk that produces the MCP tool list (`mcp::tools`) emits an
//! OpenAPI operation per declared route instead of a tool — every function is
//! simultaneously an MCP tool at `/_riz/mcp` and an OpenAPI operation here, both
//! derived from one route table, both served as routes. Served at
//! `GET /openapi.json` (public, like `/health` and the agent card).
//!
//! OpenAPI 3.1 aligns with JSON Schema 2020-12, so the typed pieces riz already
//! knows — path params from the route templates, query params and the request
//! body from `[function.X.mcp]` — transfer with no schema translation.

use crate::config::McpToolConfig;
use crate::state::{FunctionKind, RizState};
use std::collections::HashSet;
use std::sync::Arc;

/// The per-function inputs an OpenAPI operation is built from — the same three
/// fields `tools_list_value` reads. Extracted so the document builder is a pure
/// function testable without a live `RizState`.
struct OperationSource {
    name: String,
    /// "METHOD /path" entries, exactly as `FunctionState::routes` holds them.
    routes: Vec<String>,
    mcp: Option<McpToolConfig>,
}

/// Build the OpenAPI 3.1 document for the daemon's current user functions.
pub async fn openapi_document(riz_state: &Arc<RizState>) -> serde_json::Value {
    let functions = riz_state.functions.read().await;
    let specs: Vec<OperationSource> = functions
        .iter()
        .map(|(_, f)| f)
        .filter(|f| matches!(f.kind, FunctionKind::User))
        // WebSocket functions aren't request/response HTTP — they're advertised
        // as MCP session tools, not OpenAPI operations. Skip them here.
        .filter(|f| {
            !f.config
                .as_ref()
                .map(|c| c.protocol == crate::config::Protocol::WebSocket)
                .unwrap_or(false)
        })
        .map(|f| OperationSource {
            name: f.name.clone(),
            routes: f.routes.clone(),
            mcp: f.config.as_ref().and_then(|c| c.mcp.clone()),
        })
        .collect();
    build_document(&specs)
}

/// Pure builder: `OperationSource`s → the OpenAPI document value.
fn build_document(specs: &[OperationSource]) -> serde_json::Value {
    let mut paths = serde_json::Map::new();
    let mut seen_op_ids: HashSet<String> = HashSet::new();

    for src in specs {
        for route in &src.routes {
            let Some((method, path)) = split_route(route) else {
                continue;
            };
            for m in expand_method(method) {
                let op = build_operation(src, &m, path, &mut seen_op_ids);
                let item = paths
                    .entry(path.to_string())
                    .or_insert_with(|| serde_json::Value::Object(serde_json::Map::new()));
                if let Some(obj) = item.as_object_mut() {
                    obj.insert(m.to_ascii_lowercase(), op);
                }
            }
        }
    }

    serde_json::json!({
        "openapi": "3.1.0",
        "info": {
            "title": "riz",
            "version": env!("CARGO_PKG_VERSION"),
            "description": "Autogenerated from the riz function route table. Every function is \
                            an HTTP operation here and an MCP tool at /_riz/mcp — one route \
                            table, two surfaces.",
        },
        "paths": serde_json::Value::Object(paths),
    })
}

/// Build one OpenAPI operation object for a (function, method, path).
fn build_operation(
    src: &OperationSource,
    method: &str,
    path: &str,
    seen: &mut HashSet<String>,
) -> serde_json::Value {
    let mut op = serde_json::Map::new();
    op.insert(
        "operationId".into(),
        serde_json::json!(op_id(&src.name, method, path, seen)),
    );
    op.insert("summary".into(), serde_json::json!(summary(src, method)));
    // Group operations by their function so tooling can cluster them.
    op.insert("tags".into(), serde_json::json!([src.name]));

    let mut parameters: Vec<serde_json::Value> = Vec::new();
    for pname in path_param_names(path) {
        parameters.push(serde_json::json!({
            "name": pname,
            "in": "path",
            "required": true,
            "schema": { "type": "string" },
        }));
    }
    if let Some(mcp) = &src.mcp {
        for (qname, spec) in &mcp.query {
            let mut param = serde_json::json!({
                "name": qname,
                "in": "query",
                "required": spec.required,
                "schema": { "type": spec.kind },
            });
            if let (Some(obj), Some(desc)) = (param.as_object_mut(), &spec.description) {
                obj.insert("description".into(), serde_json::json!(desc));
            }
            parameters.push(param);
        }
    }
    if !parameters.is_empty() {
        op.insert("parameters".into(), serde_json::Value::Array(parameters));
    }

    // A typed request body — only for body-bearing methods, and only when the
    // function declared one. `[function.X.mcp].body` is already verbatim JSON
    // Schema (2020-12), which OpenAPI 3.1 accepts unchanged.
    if method_has_body(method) {
        if let Some(body) = src.mcp.as_ref().and_then(|m| m.body.clone()) {
            op.insert(
                "requestBody".into(),
                serde_json::json!({
                    "required": true,
                    "content": { "application/json": { "schema": body } },
                }),
            );
        }
    }

    op.insert(
        "responses".into(),
        serde_json::json!({ "200": { "description": "Successful response" } }),
    );
    serde_json::Value::Object(op)
}

/// A human summary — the `[function.X.mcp]` description if set, else generated.
fn summary(src: &OperationSource, method: &str) -> String {
    match src.mcp.as_ref().and_then(|m| m.description.clone()) {
        Some(d) => d,
        None => format!("{method} handler for function `{}`", src.name),
    }
}

/// Split a "METHOD /path" route entry. `None` for a malformed entry (skipped).
fn split_route(route: &str) -> Option<(&str, &str)> {
    route.split_once(' ').map(|(m, p)| (m.trim(), p.trim()))
}

/// Expand a route method into OpenAPI operation methods. `ANY` (riz's
/// match-all default) becomes the standard method set, since OpenAPI has no
/// "any" operation; a concrete method maps to itself.
fn expand_method(method: &str) -> Vec<String> {
    if method.eq_ignore_ascii_case("ANY") {
        ["GET", "POST", "PUT", "PATCH", "DELETE"]
            .iter()
            .map(|m| (*m).to_string())
            .collect()
    } else {
        vec![method.to_ascii_uppercase()]
    }
}

/// Body-bearing HTTP methods.
fn method_has_body(method: &str) -> bool {
    matches!(
        method.to_ascii_uppercase().as_str(),
        "POST" | "PUT" | "PATCH"
    )
}

/// A globally-unique `operationId`, preferring the cleanest form that is still
/// free. `(path, method)` is unique across an OpenAPI document, so the
/// method+path form can never collide — no numeric-suffix loop needed.
fn op_id(name: &str, method: &str, path: &str, seen: &mut HashSet<String>) -> String {
    let m = method.to_ascii_lowercase();
    let candidates = [
        name.to_string(),
        format!("{name}_{m}"),
        format!("{name}_{m}_{}", path_slug(path)),
    ];
    for candidate in candidates {
        if seen.insert(candidate.clone()) {
            return candidate;
        }
    }
    // Unreachable in practice (the 3rd form is unique by construction); return
    // it rather than panic to honor the no-panic rule.
    let last = format!("{name}_{m}_{}", path_slug(path));
    seen.insert(last.clone());
    last
}

/// Slugify a path into an operationId-safe token: non-alphanumerics → `_`.
fn path_slug(path: &str) -> String {
    let slug: String = path
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    slug.trim_matches('_').to_string()
}

/// Extract `{name}` / `{name+}` path-parameter names from a path template, in
/// declaration order. Mirrors `mcp::schema::path_param_names` (same `{param}`
/// syntax OpenAPI itself uses); kept local to avoid exposing mcp internals.
fn path_param_names(path: &str) -> Vec<String> {
    path.trim_start_matches('/')
        .split('/')
        .filter_map(|seg| {
            seg.strip_prefix('{').and_then(|s| {
                s.strip_suffix("+}")
                    .or_else(|| s.strip_suffix('}'))
                    .map(str::to_string)
            })
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn src(name: &str, routes: &[&str], mcp_toml: Option<&str>) -> OperationSource {
        OperationSource {
            name: name.to_string(),
            routes: routes.iter().map(|r| r.to_string()).collect(),
            mcp: mcp_toml.map(|t| toml::from_str(t).expect("mcp parses")),
        }
    }

    #[test]
    fn document_has_operation_per_route_with_path_params() {
        let doc = build_document(&[src(
            "orders",
            &["GET /orders/{id}"],
            Some(r#"description = "Fetch an order""#),
        )]);
        assert_eq!(doc["openapi"], "3.1.0");
        let op = &doc["paths"]["/orders/{id}"]["get"];
        assert_eq!(op["operationId"], "orders");
        assert_eq!(op["summary"], "Fetch an order");
        // The path param is a required OpenAPI parameter.
        let param = &op["parameters"][0];
        assert_eq!(param["name"], "id");
        assert_eq!(param["in"], "path");
        assert_eq!(param["required"], true);
        assert!(op["responses"]["200"].is_object());
    }

    #[test]
    fn query_params_and_typed_body_transfer_from_mcp() {
        let doc = build_document(&[src(
            "search",
            &["POST /search"],
            Some(
                r#"
body = { type = "object", properties = { q = { type = "string" } } }

[query.limit]
type = "integer"
required = true
description = "max results"
"#,
            ),
        )]);
        let op = &doc["paths"]["/search"]["post"];
        let q = &op["parameters"][0];
        assert_eq!(q["name"], "limit");
        assert_eq!(q["in"], "query");
        assert_eq!(q["required"], true);
        assert_eq!(q["schema"]["type"], "integer");
        assert_eq!(q["description"], "max results");
        // The mcp body (verbatim JSON Schema) becomes the requestBody schema.
        assert_eq!(
            op["requestBody"]["content"]["application/json"]["schema"]["properties"]["q"]["type"],
            "string"
        );
    }

    #[test]
    fn any_method_expands_to_the_standard_set_with_unique_op_ids() {
        let doc = build_document(&[src("ping", &["ANY /ping"], None)]);
        let item = doc["paths"]["/ping"].as_object().unwrap();
        for m in ["get", "post", "put", "patch", "delete"] {
            assert!(item.contains_key(m), "ANY should emit {m}");
        }
        // GET carries no request body; POST/PUT/PATCH may.
        assert!(item["get"].get("requestBody").is_none());
        // operationIds are unique across the expansion.
        let mut ids: Vec<&str> = item
            .values()
            .filter_map(|op| op["operationId"].as_str())
            .collect();
        let count = ids.len();
        ids.sort_unstable();
        ids.dedup();
        assert_eq!(ids.len(), count, "operationIds must be unique");
    }

    #[test]
    fn path_params_parse_plain_and_greedy() {
        assert_eq!(path_param_names("/a/{id}/b/{key+}"), vec!["id", "key"]);
        assert!(path_param_names("/static/path").is_empty());
    }
}
