#!/usr/bin/env bash
# Power of 10 safety checks (docs/SAFETY.md) — production code only.
#
# Scope is the code compiled into the riz binary (--lib --bins). Tests,
# benches, and the example lambdas are exempt by policy; the enforced lint
# tier that covers all targets lives in Cargo.toml [workspace.lints].
#
# Modes:
#   scripts/safety-check.sh          Ratchet report (non-gating, exit 0):
#                                    violation counts for the burn-down tier,
#                                    bucketed per rule/lint and per module.
#                                    A lint whose count reaches zero gets
#                                    promoted: first into GATE_LINTS here,
#                                    then into [workspace.lints] once test
#                                    code also passes it.
#   scripts/safety-check.sh --gate   Zero-tolerance gate (CI): lints that are
#                                    clean in production code today and must
#                                    stay clean, but that test helpers
#                                    legitimately use — so they cannot be
#                                    denied workspace-wide. Fails on any hit.

set -euo pipefail
cd "$(dirname "$0")/.."

# Clean in src/ today; test helper code panics by design (assertion style).
GATE_LINTS=(
  clippy::panic
  clippy::disallowed_methods  # rule 3 — unbounded channels; reached zero 2026-07-03
  clippy::unwrap_used         # rule 7 — recoverable paths must return Err; reached zero 2026-07-06
  clippy::expect_used         # rule 7 — ditto; reached zero 2026-07-06
  clippy::unreachable         # rule 7 — prove it or return an error; reached zero 2026-07-06
  clippy::exit                # rule 1 — exits only at CLI top level (doctor's are site-allowed deviations); reached zero 2026-07-06
  clippy::indexing_slicing    # rule 9 — .get() over panicking access; reached zero 2026-07-06
  clippy::arithmetic_side_effects # rule 5 — checked/saturating arithmetic; reached zero 2026-07-06
  clippy::too_many_lines          # rule 4 — threshold in clippy.toml; reached zero 2026-07-06
  clippy::cognitive_complexity    # rule 4 — threshold in clippy.toml; reached zero 2026-07-06
)

# Ratchet completed 2026-07-06: the 253 sites baselined on 2026-07-03 are at
# zero and every burned-down lint has been promoted into GATE_LINTS above
# (PRs #30/#31/#32/#33/#37/#41/#42 + the structure pass). The report mode
# below now just confirms the tier stays empty; if a lint ever needs
# ratcheting again, list it here and move it out of the gate.
RATCHET_LINTS=()

if [[ "${1:-}" == "--gate" ]]; then
  flags=()
  for lint in "${GATE_LINTS[@]}"; do flags+=("-D" "$lint"); done
  echo "safety gate (--lib --bins): ${GATE_LINTS[*]}"
  cargo clippy --lib --bins --quiet -- "${flags[@]}"
  echo "safety gate: PASS"
  exit 0
fi

# The ${arr[@]+...} guards keep `set -u` happy on bash 3.2 (macOS default)
# when the ratchet list is empty.
flags=()
for lint in ${RATCHET_LINTS[@]+"${RATCHET_LINTS[@]}"}; do flags+=("-W" "$lint"); done

# One line per unique violation site: "<lint>\t<file>\t<line>". The lib and
# bin targets compile the same files twice, so diagnostics are deduplicated by
# site. `cargo clippy` exits 0 here — ratchet lints are warnings, and the
# enforced tier is already clean.
raw=$(cargo clippy --lib --bins --quiet --message-format=json -- ${flags[@]+"${flags[@]}"} 2>/dev/null |
  jq -r 'select(.reason=="compiler-message") | (.message.code.code // empty) as $c
         | select($c != "")
         | $c + "\t" + (.message.spans[0].file_name // "?")
              + "\t" + (.message.spans[0].line_start // 0 | tostring)' | sort -u)

echo "Power of 10 ratchet report — production code (--lib --bins)"
echo "generated by scripts/safety-check.sh; policy in docs/SAFETY.md"
echo
echo "== violations per lint =="
if [[ -z "$raw" ]]; then
  echo "(none — promote the ratchet tier and delete this script's list)"
  exit 0
fi
sort <<<"$raw" | cut -f1 | uniq -c | sort -rn

echo
echo "== violations per module x lint =="
# Module = first path component under src/ (src/ws/store.rs -> ws,
# src/cache.rs -> cache).
awk -F'\t' '{
  path = $2; sub(/^src\//, "", path); sub(/\.rs$/, "", path)
  split(path, parts, "/"); print parts[1] "\t" $1
}' <<<"$raw" | sort | uniq -c | sort -k2,2 -k1,1rn | awk '{printf "%6d  %-16s %s\n", $1, $2, $3}'

echo
echo "total: $(wc -l <<<"$raw" | tr -d ' ')"
