//! `riz scaffold static` — generate the agent-discovery surface from config.
//!
//! See the v2 section of
//! `docs/superpowers/specs/2026-06-18-static-serving-design.md`.
//!
//! A live riz instance can describe itself: pointed at `[static]`, it serves
//! its own `llms.txt` and `.well-known/riz.json` so an agent that fetches
//! `https://my-host/` discovers the when-to-use card and the `/_riz/mcp`
//! endpoint with no separate marketing site. This module DERIVES those two
//! files from the project's `riz.toml` — every `[function.*]` becomes a tool
//! entry whose name, runtime, routes, and description match exactly what the
//! running MCP server (`src/system/mcp/tools.rs`) advertises.
//!
//! The generators are pure (`Config` → `String`) so they're unit-testable
//! without touching the filesystem; `scaffold_static` is the thin IO wrapper
//! the CLI calls.

use crate::config::{Config, FunctionConfig, RouteSpec};
use std::path::{Path, PathBuf};

/// The MCP endpoint every riz instance exposes — kept in one place so the two
/// generated files (and the docs) never drift.
const MCP_ENDPOINT: &str = "/_riz/mcp";
/// Current default MCP spec version (mirrors `src/system/mcp`).
const MCP_SPEC: &str = "2025-11-25";

/// One generated tool entry, shared by both renderers so llms.txt and
/// riz.json describe the identical surface.
struct ToolEntry {
    name: String,
    runtime: String,
    routes: Vec<RouteSpec>,
    description: String,
}

/// Build the tool list from the user functions, in declared (IndexMap) order.
/// Mirrors `tools.rs`: tool name = function name; the `[function.x.mcp]`
/// description wins, else the generated "Invoke function ..." line.
fn tool_entries(config: &Config) -> Vec<ToolEntry> {
    config
        .functions
        .iter()
        .map(|(name, func)| {
            let routes = func.effective_routes(name);
            ToolEntry {
                name: name.clone(),
                runtime: func.runtime.as_str().to_string(),
                description: tool_description(name, func, &routes),
                routes,
            }
        })
        .collect()
}

/// The exact description the live MCP server would advertise for this function.
fn tool_description(name: &str, func: &FunctionConfig, routes: &[RouteSpec]) -> String {
    if let Some(d) = func.mcp.as_ref().and_then(|m| m.description.clone()) {
        return d;
    }
    let route_list = routes
        .iter()
        .map(|r| format!("{} {}", r.method, r.path))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "Invoke function `{}` ({} runtime). Routes: [{}]",
        name,
        func.runtime.as_str(),
        route_list
    )
}

/// Render `llms.txt` for this instance — the agent-readable when-to-use card.
pub fn generate_llms_txt(config: &Config) -> String {
    let tools = tool_entries(config);
    let mut out = String::new();
    out.push_str("# riz instance\n\n");
    out.push_str(&format!(
        "> A self-hosted riz runtime exposing {} function{} as typed MCP tools \
         at `{MCP_ENDPOINT}`. Every HTTP handler below is callable by an agent \
         the moment this instance is reachable — zero glue.\n\n",
        tools.len(),
        if tools.len() == 1 { "" } else { "s" }
    ));
    out.push_str(
        "This file is served by the instance itself (riz `[static]`), so pointing an \
         agent at this host is enough to discover its tools and the MCP endpoint. \
         Handlers speak the AWS API Gateway v2 wire shape.\n\n",
    );

    out.push_str("## Tools\n\n");
    if tools.is_empty() {
        out.push_str(
            "_No functions are configured yet. Add a `[function.<name>]` block to \
             riz.toml and re-run `riz scaffold static`._\n\n",
        );
    } else {
        for t in &tools {
            out.push_str(&format!("### {}\n\n", t.name));
            out.push_str(&format!("- runtime: `{}`\n", t.runtime));
            let routes = t
                .routes
                .iter()
                .map(|r| format!("`{} {}`", r.method, r.path))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("- routes: {routes}\n"));
            out.push_str(&format!("- {}\n\n", t.description));
        }
    }

    out.push_str("## MCP endpoint\n\n");
    out.push_str(&format!(
        "- `POST {MCP_ENDPOINT}` — JSON-RPC 2.0 over Streamable HTTP (MCP spec {MCP_SPEC}).\n\
         - Methods: `initialize`, `tools/list`, `tools/call`, `resources/list`, `prompts/list`.\n\
         - Wire up: `claude mcp add riz --transport http <this-host>{MCP_ENDPOINT}`.\n\n"
    ));

    out.push_str("## Generated\n\n");
    out.push_str(
        "This file was generated by `riz scaffold static` from riz.toml. \
         Re-run it after changing your functions to keep the tool list in sync.\n",
    );
    out
}

/// Render `.well-known/riz.json` — the machine-readable instance card.
pub fn generate_well_known(config: &Config) -> String {
    let tools: Vec<serde_json::Value> = tool_entries(config)
        .into_iter()
        .map(|t| {
            let routes: Vec<serde_json::Value> = t
                .routes
                .iter()
                .map(|r| serde_json::json!({ "method": r.method.clone(), "path": r.path.clone() }))
                .collect();
            serde_json::json!({
                "name": t.name,
                "runtime": t.runtime,
                "routes": routes,
                "description": t.description,
            })
        })
        .collect();

    let doc = serde_json::json!({
        "name": "riz",
        "tagline": "Self-hosted AWS Lambda runtime where every function becomes a typed MCP tool.",
        "description": "A live riz instance. Every function below is a typed MCP tool callable \
                        at the MCP endpoint — no SDK, no glue.",
        "mcp": {
            "endpoint": MCP_ENDPOINT,
            "transport": "JSON-RPC 2.0 over Streamable HTTP",
            "spec": MCP_SPEC,
        },
        "tools": tools,
        "generated_by": "riz scaffold static",
    });

    // Pretty-print with a trailing newline (POSIX text file).
    let mut s = serde_json::to_string_pretty(&doc).expect("scaffold json is serializable");
    s.push('\n');
    s
}

/// What `scaffold_static` produced, for the CLI to report.
#[derive(Debug)]
pub struct ScaffoldResult {
    pub written: Vec<PathBuf>,
    pub wired: bool,
}

/// Options for `scaffold_static`.
pub struct ScaffoldOptions {
    /// Target site root (e.g. `public`).
    pub dir: PathBuf,
    /// Mount value to write into a `[static]` block when `wire` is set.
    pub mount: String,
    /// Append a `[static]` block to `config_path` if one isn't present.
    pub wire: bool,
    /// Overwrite existing generated files.
    pub force: bool,
}

/// Generate `dir/llms.txt` + `dir/.well-known/riz.json` from `config`, and
/// (when `wire`) ensure `config_path` carries a `[static]` block pointing at
/// `dir`. Refuses to clobber existing files unless `force`.
pub fn scaffold_static(
    config: &Config,
    config_path: &Path,
    opts: &ScaffoldOptions,
) -> anyhow::Result<ScaffoldResult> {
    let well_known_dir = opts.dir.join(".well-known");
    let llms_path = opts.dir.join("llms.txt");
    let riz_json_path = well_known_dir.join("riz.json");

    if !opts.force {
        for p in [&llms_path, &riz_json_path] {
            if p.exists() {
                anyhow::bail!(
                    "refusing to overwrite existing file: {}. Re-run with --force to replace it.",
                    p.display()
                );
            }
        }
    }

    std::fs::create_dir_all(&well_known_dir)?;
    std::fs::write(&llms_path, generate_llms_txt(config))?;
    std::fs::write(&riz_json_path, generate_well_known(config))?;

    let mut wired = false;
    if opts.wire {
        wired = wire_static_block(config, config_path, &opts.dir, &opts.mount)?;
    }

    Ok(ScaffoldResult {
        written: vec![llms_path, riz_json_path],
        wired,
    })
}

/// Append a `[static]` block to `config_path` unless one is already configured.
/// Returns true if the block was written, false if static was already set.
fn wire_static_block(
    config: &Config,
    config_path: &Path,
    dir: &Path,
    mount: &str,
) -> anyhow::Result<bool> {
    if config.static_site.is_some() {
        return Ok(false);
    }
    let mut text = std::fs::read_to_string(config_path).map_err(|e| {
        anyhow::anyhow!(
            "could not read {} to wire [static]: {e}",
            config_path.display()
        )
    })?;
    if !text.ends_with('\n') {
        text.push('\n');
    }
    text.push_str(&format!(
        "\n# Added by `riz scaffold static` — colocate the site + serve the\n\
         # instance's own llms.txt / .well-known/riz.json on this binary.\n\
         [static]\n\
         dir = {:?}\n\
         mount = {:?}\n",
        dir.display().to_string(),
        mount
    ));
    std::fs::write(config_path, text)?;
    Ok(true)
}
